config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#root'

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  post '/pusher/auth'

  namespace :api, default: { format: :json } do
    resources :two_player_games, only: [:new]

    namespace :leaders, default: {format: :json} do
      resources :beginner_leaders, only: [:index, :create]
      resources :intermediate_leaders, only: [:index, :create]
      resources :expert_leaders, only: [:index, :create]
    end
  end
end

app/models/beginner_leader.rb
class BeginnerLeader < ActiveRecord::Base

  validates :name, :time, presence: true

end

app/models/expert_leader.rb
class ExpertLeader < ActiveRecord::Base

  validates :name, :time, presence: true

end

app/models/intermediate_leader.rb
class IntermediateLeader < ActiveRecord::Base

  validates :name, :time, presence: true

end

app/models/two_player_game.rb
class TwoPlayerGame < ActiveRecord::Base

  validates :game_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :session_token, :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def User.find_by_credentials(username, password)
    user = User.find_by_username(username)

    if user && user.is_password?(password)
      return user
    end

    nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private

    def ensure_session_token
      self.session_token ||= SecureRandom.urlsafe_base64
    end

end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/two_player_games_controller.rb
class Api::TwoPlayerGamesController < ApplicationController

  def new
    game_id = SecureRandom.urlsafe_base64
    @two_player_game = TwoPlayerGame.new({ game_id: game_id })

    @two_player_game.save
    render json: @two_player_game
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in_check
    redirect_to new_session_url unless current_user
  end

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id],
        { :user_id => current_user.id })

      render :json => response
    else # Let guests use it too
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id],
        { :user_id => SecureRandom.urlsafe_base64 })

      render :json => response
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      log_in(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  def new
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_check, only: [:show]

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/helpers/api/leaders/expert_leaders_helper.rb
module Api::Leaders::ExpertLeadersHelper
end

app/helpers/api/two_player_games_helper.rb
module Api::TwoPlayerGamesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{ form_authenticity_token }\">".html_safe
  end

end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MinesweeperLeague</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//js.pusher.com/2.2/pusher.min.js"></script>
  <%= javascript_tag "window.pusherKey = '" + Pusher.key + "'" %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/#">
          <img alt="Brand" src="<%= asset_path('MSL-logo.png') %>"/>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/#">Single Player</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
                Competitive <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/#two_player/beginner/new">Beginner</a></li>
              <li><a href="/#two_player/intermediate/new">Intermediate</a></li>
              <li><a href="/#two_player/expert/new">Expert</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Profile Page", user_url(current_user) %></li>
            <li><%= link_to "Sign Out", session_url, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_session_url %></li>
            <li><%= link_to "Sign Up", new_user_url %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if flash[:errors] %>
    <div class="flash-container container">
      <div class="flash-row row">
        <div class="flash-col col-md-12">
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <strong>Uh Oh!</strong>
            <%= flash[:errors].join('<br>').html_safe if flash[:errors] %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>